orvibo_asyncio_remote_learn:
  # Description of the service
  description: Learns keys for the remote
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name of the remote to use for learning
      # Example value that can be passed for this field
      example: 'remote.diningroom'
    timeout:
      description: (Optional, Default=30) maximum time in seconds to wait for key
      example: 40
    keys:
      description: (Optional, Default=['NA_1']) list of the names of the keys to learn
      example: ['volume_up','volume_down','ch0']

orvibo_asyncio_remote_discovery:
  # Description of the service
  description: Discovers new Orvibo Allone
  # Different fields that your service accepts
  fields:
    tiimeout:
      description: (Optional, Default=10) time in seconds to wait for new devices to show
      example: 30
    broadcast_address:
      description: (Optional, Default='255.255.255.255') broadcast IP address to use for discovery
      example: '192.168.25.255'

orvibo_asyncio_switch_discovery:
  # Description of the service
  description: Discovers new Orvibo Allone
  # Different fields that your service accepts
  fields:
    tiimeout:
      description: (Optional, Default=10) time in seconds to wait for new devices to show
      example: 30
    broadcast_address:
      description: (Optional, Default='255.255.255.255') broadcast IP address to use for discovery
      example: '192.168.25.255'
